spring:
  application:
    name: kafka
  datasource:
    url: jdbc:postgresql://localhost:5432/rb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
kafka:
  servers: localhost:9092
  groupId: RuslanGroup
  topicName: Ruslan-topic
  autoOffsetReset: earliest
